org.quartz.scheduler.instanceName = Sched1
org.quartz.scheduler.instanceId = 1
org.quartz.scheduler.rmi.export = false
org.quartz.scheduler.rmi.proxy = false

org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 4

org.quartz.jobStore.class = org.quartz.simpl.RAMJobStore
#org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.MSSQLDelegate
#org.quartz.jobStore.useProperties = false
#org.quartz.jobStore.tablePrefix = QRTZ_
#org.quartz.jobStore.isClustered = false
#org.quartz.jobStore.dataSource = myCustomDS
#org.quartz.jobStore.lockHandler.class = org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore
#org.quartz.dataSource.myCustomDS.connectionProvider.class = com.consilux.lib.QuartzConnectionProvider
#org.quartz.scheduler.skipUpdateCheck = true
#org.quartz.jobStore.lockHandler.updateLockRowSQL = UPDATE QRTZ_LOCKS SET LOCK_NAME = LOCK_NAME WHERE LOCK_NAME = ?