<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://server.ws.consilux.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://server.ws.consilux.com" xmlns:intf="http://server.ws.consilux.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://server.ws.consilux.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="registrarEvento">
    <complexType>
     <sequence>
      <element name="xmlCSXEvent" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="registrarEventoResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="registrarEventoRequest">

      <wsdl:part element="impl:registrarEvento" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="registrarEventoResponse">

      <wsdl:part element="impl:registrarEventoResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="CSXEventsWS">

      <wsdl:operation name="registrarEvento">

         <wsdl:input message="impl:registrarEventoRequest" name="registrarEventoRequest"/>

         <wsdl:output message="impl:registrarEventoResponse" name="registrarEventoResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="CSXEventsWSSoapBinding" type="impl:CSXEventsWS">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="registrarEvento">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="registrarEventoRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="registrarEventoResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="CSXEventsWSService">

      <wsdl:port binding="impl:CSXEventsWSSoapBinding" name="CSXEventsWS">

         <wsdlsoap:address location="http://localhost/services/CSXEventsWS"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
