#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
		# Porta que o Nginx vai usar para aceitar conexões e posteriormente redirecionar para o Tomcat e/ou câmeras
        listen 8185;
		# Logs
		#access_log logs/access.log main;
	
        # Proxy reverso para o Tomcat rodando na porta 64000
        location / {
			proxy_pass http://127.0.0.1:64000;
			
			# Cabeçalhos padrões para proxy HTTP
			proxy_set_header Host $host:$server_port;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			
			# Suporte para WebSocket
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";

			# Timeouts para manter a conexão WebSocket ativa
			proxy_read_timeout 86400;
			proxy_send_timeout 86400;
		}
		
        # Redirecionamento para as câmeras
        location ~ /RPC2|RPC2_Login|RPC_Loadfile/ {
            proxy_pass http://$http_self_targetip;
            break;
        }
		
		# Usando regex para capturar o IP e a porta da URL
		# Requisições webservice externa virão no seguinte formato
		# ws://189.112.204.89:8000/10.0.5.50:80/rtspoverwebsocket
		# onde 189.112.204.89:8000 é o servidor Nginx
		# e 10.0.5.50:80 é a câmera na rede local
		location ~ /(?<camera_ip>[0-9\.]+):(?<camera_port>[0-9]+)/rtspoverwebsocket {
			
			# Usando as variáveis $camera_ip e $camera_port capturadas
			set $target "http://$camera_ip:$camera_port";
			
			proxy_pass $target;
			
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
		
		# Configuração para RTSP
		location ~ /(?<camera_ip>[0-9\.]+):(?<camera_port>[0-9]+)/cam/realmonitor {
			
			# Usando as variáveis $camera_ip e $camera_port capturadas
			set $target "http://$camera_ip:$camera_port";
			
			proxy_pass $target;
			
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }
    }
}
